---

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1

  document-start: disable

  empty-lines:
    max: 1

  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
    level: warning

  new-line-at-end-of-file: enable
